version: '3.1'
services:
  DATABASE:
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_accounttt
    networks:
      - db

  SERVER:
    container_name: bank_acc
    image: bank_acc
    build: ./
    ports:
      - "7575:7575"
    depends_on:
      - DATABASE
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5444/bank_accounttt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #      - SPRING_FLYWAY_URL=jdbc:postgresql://localhost:5432/bank_account
  #      - SPRING_FLYWAY_USER=postgres
  #      - SPRING_FLYWAY_PASSWORD=postgres

networks:
  db:
    driver: bridge
