version: '3.1'
services:
  PostgreSQL:
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_account_db
    restart: always
    volumes:
      - habrdb-data:/var/lib/postgresql/data
  API:
    container_name: bank_acc
    image: bank_acc
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/bank_account_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    volumes:
      - ./logs:/Server/logs

volumes:
  habrdb-data: