version: '3.1'
services:
  PostgreSQL:
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_accounttt

  API:
    container_name: bank_acc
    image: bank_acc
    build: ./
    ports:
      - "7575:7575"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/bank_accounttt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
